### PR TITLE
update terminal css and js files

### PR DESCRIPTION
**Pull request by artembo**
Safari memory leaking issue was resolved in the new version of jquery.terminal

### CODE REVIEW

**Comment by Totktonada** [comment]
@artembo Please, add the reason of the commit (Safari memleak) to the commit message. It is often hard to understand **why** a change was made after some time.

**Comment by Totktonada** [comment]
It is better then was. You can split it into two lines: header and body—to keep the header within 50 symbols length. Just as you do it for the PR title / description :)

**Comment by artembo** [comment]
Hope it's looking good now

**Comment by Totktonada** [comment]
Ok.

**Pull request merged**
